### ISSUE TITLE
injecting and minification

### ISSUE THREAD

**Issue by artemjackson** [ssnau/injecting#1]
First of all thank you for the nice di.

Let us take the code from the [README](https://github.com/ssnau/injecting/blob/master/README.md#example) example
```
var injecting = require('injecting');
var app = injecting();
app.register('name', 'jack');
app.register('person', function(name) {
    this.name = name;
});

app.invoke(function(person) {
    console.log(person.name); // jack
});
```
after minification it will be something like this
```
var injecting = require("injecting"),
    app = injecting();
app.register("name","jack");
app.register("person",function(n){this.name=n});
app.invoke(function(n){console.log(n.name)});
```
The code above will throw an error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: n is not found!`, because the function property `name` was replaced with `n` after minification.

So the question is: is there any workaround to deal with minification?

**Comment by ssnau** [comment]
Thanks @artemjackson .

There are several ways to inject pre-defined dependencies.

```
// invoke a function
app.invoke(['person', function(p) {
  console.log(p);
});

// register a service in array form
app.register('person', ['name', 'age', function(n, a) {
  return {name: n, age: a};
});
```

make sure you update your `injecting` to `2.4.0`.

**Comment by artemjackson** [comment]
@ssnau 

Good job!
