### ISSUE TITLE
设置 overwritable 为true，再次register时，报循环引用的错

### ISSUE THREAD

**Issue by chenhebing** [ssnau/injecting#4]
你好，我需要多次注册一个 name。如果其对应为service，并且如果已经调用了invoke，即使设置了overwritable，依然会报错，想请教下，这种情况应该怎么来处理？如果是service的话，之前的name不能再被覆盖了吗？下面是测试代码：

```js
//story.js
module.exports = function(place, person){
    return {
        place: place,
        person: person.name,
        pet: person.pet.name
    };
};

// index.js
var injecting = require('injecting');
var app = injecting();
app.register('place', 'pacific');
app.register('cat', function() {
    this.name = "white cat";
});
app.register('person', function(cat) {
    this.name = "robot";
    this.pet = cat;
});
let story = require('./story');
app.register('story', story, {
    overwritable: true
});
app.invoke(function(story){
    console.log(story);
});

app.register('story', story);
app.invoke(function(story){
    console.log(story);
});
```

**Comment by chenhebing** [comment]
主要是下面这边报错的，按我的理解是，invoke一次后，就会loading name，再次invoke的，就会报错。我去掉了下面这段，执行也没问题，请教下，下面这段代码当时的初衷是什么？谢谢！
```js
 app._loading = app._loading || {};
if (app._loading[name]) throw new Error('circular dependencies found for ' + name);
app._loading[name] = true;
```

**Comment by ssnau** [comment]
hi @chenhebing 报歉 长时间未登github. 回答一下你的问题：
1. `_loading`主要是为了防止循环引用的，由于函数的结果会被cache, 所以它最多只会被执行一次。
2. 如果一个`injector`对应的某个name已经被invoke过，则不应该再overwrite它。因为这会导致你运行时的`story`在不同闭包下不一致，这样的bug也几乎难以预测和捕获。只有当一个name没有被inovke过，overwrite它才会是安全的。

希望上面的解释对你有帮助。

**Comment by chenhebing** [comment]
> hi @chenhebing 报歉 长时间未登github，也许久不碰前端了，回答一下你的问题：
> 
> 1. `_loading`主要是为了防止循环引用的，由于函数的结果会被cache, 所以它最多只会被执行一次。
> 2. 如果一个`injector`对应的某个name已经被invoke过，则不应该再overwrite它。因为这会导致你运行时的`story`在不同闭包下不一致，这样的bug也几乎难以预测和捕获。只有当一个name没有被inovke过，overwrite它才会是安全的。
> 
> 希望上面的解释对你有帮助。

懂了 非常感谢！！！
